#!/usr/bin/env bash

declare -A layouts=(
    ["English (UK)"]="gb"
    ["Arabic"]="ara"
)

lines=${#layouts[@]}

choice=$(printf '%s\n' "${!layouts[@]}" |
    dmenu -c -i -l "$lines" -p "Keyboard layout:")

[ -z "$choice" ] && exit 0

setxkbmap "${layouts[$choice]}"
