#!/usr/bin/env bash

choice=$(printf '%s\n' \
    "󰐥 Shutdown" \
    " Restart" \
    " Lock" \
    "󰤄 Sleep" |
    dmenu -c -bw 3 -i -l 2 -F -g 2 -p "Power:")

case "$choice" in
    "󰐥 Shutdown")
        loginctl poweroff 
        ;;
    " Restart")
        loginctl reboot
        ;;
    " Lock")
        slock
        ;;
    "󰤄 Sleep")
        loginctl suspend
        ;;
esac
