#!/usr/bin/env bash

# symlinking dunstrc
ln -sf ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc
pkill dunst; setsid -f dunst

# Reload Xresources database with pywal colors
xrdb -merge ~/.cache/wal/colors.Xresources

# refreshing with xrdb
xdotool key --clearmodifiers super+BackSpace

notify-send "Wallpaper and colourscheme changed"
