#!/bin/sh

# Fetch volume of current default sink
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'/' '{print $2}' | head -n 1 | tr -d ' ')
muted=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o "yes")

case $BLOCK_BUTTON in
		1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
		2) setsid -f alsamixer ;;
		3) notify-send "Volume" "$vol" ;;
		4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
		5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
		6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if [ "$muted" = "yes" ]; then
    echo "󰝟 "
else
    echo "󰕾 $vol"
fi
