#!/bin/sh

# Fetch volume and mute status of current default sink
vol_info=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
vol=$(echo "$vol_info" | awk '{print int($2 * 100)"%"}')
muted=$(echo "$vol_info" | grep -o "\[MUTED\]")

case $BLOCK_BUTTON in
		1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
		3) setsid -f pavucontrol ;;
		2) notify-send "Volume" "$vol" ;;
		4) wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ ;;
		5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- ;;
		6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if [ "$muted" = "[MUTED]" ]; then
    echo "󰝟 "
else
    echo "󰕾 $vol"
fi
