#!/usr/bin/env bash

layout=$(setxkbmap -query | awk '/^layout:/ {print $2}')

case "$layout" in
    gb)
        printf "GB"
        ;;
    ara)
        printf "ةيبرعلا"
        ;;
    *)
        printf "%s" "$layout"
        ;;
esac
