#!/usr/bin/env bash

statefile="$HOME/.cache/current-layout"

case "$(cat "$statefile" 2>/dev/null)" in
    gb)
        printf "GB"
        ;;
    ara)
        printf "AR"
        ;;
    *)
        printf "??"
        ;;
esac
