#!/bin/sh

# Fetch volume of current default sink
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'/' '{print $2}' | head -n 1 | tr -d ' ')
muted=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o "yes")

if [ "$muted" = "yes" ]; then
    echo "󰝟 Muted"
else
    echo "󰕾 $vol"
fi
