#!/bin/sh

url=$1
action=$2

case "$action" in
    v|video)
        exec mpv "$url"
        ;;

    a|audio)
        exec mpv --no-video "$url"
        ;;

    V|download)
        exec yt-dlp "$url"
        ;;

    A|audio-download)
        exec yt-dlp -x "$url"
        ;;

    *)
        printf '%s\n' "Usage: vimb-media URL {v|a|V|A}" >&2
        exit 1
        ;;
esac
