#!/usr/bin/env bash

# slightly scuffed wallpaper picker menu for use with pywal - uses nsxiv if installed, otherwise uses dmenu

FOLDER=~/pictures/wallpapers # wallpaper folder
SCRIPT=~/dotfiles/scripts/pywal16 # script to run after wal for refreshing programs, etc.

menu () {
				CHOICE=$(nsxiv -otb $FOLDER/*)

case $CHOICE in
		*.*) wal -i "$CHOICE" -o $SCRIPT ;;
		*) exit 0 ;;
esac
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
		0) menu ;;
		1) wal -i "$1" -o $SCRIPT ;;
		2) wal -i "$1" --theme $2 -o $SCRIPT ;;
		*) exit 0 ;;
esac
