# Fonts
[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Bold Italic"

[window]
opacity = 0.75
